# Set theme
theme: garth-jekyll-theme

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-paginate

# Site settings
url: 'https://blog.gabinnshimirimana.com/'
baseurl: ''
title: 'Gabin Nshimirimana'
description: 'This is my new blog'
permalink: pretty
logo: "https://gabinnshimirimana.com/images/gabin_nshimirimana_headshot.png"

# Pagination
paginate: 5
paginate_path: blog/page:num

# Collections
collections:
  posts:
    title: Blog
    output: true
    description: "Encouraging stories"
